### ISSUE TITLE
where is the link of your website?

### ISSUE THREAD

**Issue by liamxg** [japilo/personal-website#1]
Dear @japilo,
Could I know where is the link of your website?

**Comment by japilo** [comment]
It's the website link in [my profile](https://github.com/japilo). You also could have found this information in the [hugo.yaml file](https://github.com/japilo/personal-website/blob/main/config/_default/hugo.yaml) in this repository. Please don't open issues for things that are very easy to look up.

**Comment by liamxg** [comment]
Dear @japilo,

Sorry for bother you, usually people put the website link on the top right of the repository.
